baseURL = 'https://douglas571.github.io'
languageCode = 'en-us'
title = 'Douglas Socorro'

copyright = "Copyright © 2022 Douglas Socorro"

footnote = "This site was built with Hugo, Hosted and published with GitHub."

styles = ['styles.css']
