baseURL = 'https://douglas571.github.io'
languageCode = 'en-us'
title = 'Douglas Socorro'
watch = true

copyright = "Copyright © 2022 Douglas Socorro"

[markup]
  [markup.highlight]
    noClasses=false

[params]
  

styles = ['styles.css']

